load("@rules_rust//rust:rust.bzl", "rust_analyzer")

rust_analyzer(
    name = "rust_analyzer",
    targets = [
        "//prostgen/basic:common_bin",
        "//prostgen/helloworld/greeter_client",
        "//prostgen/helloworld/greeter_server",
    ],
)